models/MemcachedConfig.php
<?php

namespace app\models;

use yii\base\Model;

/**
 * Class MemcachedConfig
 *
 * Класс для работы с текстовым конфигом мемкеша
 *
 * @package app\models
 */
class MemcachedConfig extends Model {

	const CONFIG_FILE = 'memcached.txt';
	public $config;

	/**
	 * @return array the validation rules.
	 */
	public function rules() {
		return [
			['config', 'required']
		];
	}

	/**
	 * Чтение конфига из файла
	 *
	 * @return bool успешность чтения конфига
	 */
	public function readConfig() {
		$this->config = 'File with config not exist';
		if (!file_exists(self::CONFIG_FILE)) {
			return false;
		}

		try {
			$this->config = file_get_contents(self::CONFIG_FILE);
		} catch (\Exception $e) {
			$this->config = 'Exception on read config, ' . $e->getMessage();
			return false;
		}
		return true;
	}

	/**
	 * Сохранение конфига в файл
	 *
	 * @return bool успешность чтения конфига
	 */
	public function saveConfig() {
		try {
			file_put_contents(self::CONFIG_FILE, $this->config);
		} catch (\Exception $e) {
			$this->config = 'Exception on save config, ' . $e->getMessage();
			return false;
		}
		return true;
	}

	/**
	 * Метод подготавливает текстовый конфиг к нужному формату
	 *
	 * @return array
	 */
	public function getPreparedConfig() {
		$result = [];
		$rows = explode("\n", $this->config);
		foreach ($rows as $row) {
			list($ip, $port) = explode(':', $row);
			$result[] = [
				'ip' => $ip,
				'port' => $port,
			];
		}
		return $result;
	}
}

models/MemcachedVisor.php
<?php

namespace app\models;

use yii\base\Model;


/**
 * Class MemcachedVisor
 *
 * Класс обертка над Memcached
 *
 * @package app\models
 */
class MemcachedVisor extends Model {

	public static $instance = null;

	/**
	 * MemcachedVisor constructor.
	 * @param array $config
	 */
	public function __construct($config) {

		self::$instance = new \Memcached();
		if (is_array($config) && isset($config[0]['ip'], $config[0]['port'])) {
			foreach ($config as $server) {
				self::$instance->addServer($server['ip'], intval($server['port']));
			}
		}
	}

	/**
	 * Метод возвращает статистику по серверам
	 * @return array
	 */
	public function getStats() {
		return self::$instance->getStats();
	}

	/**
	 * Метод устанавливает значение в мемкеш по ключу $key
	 *
	 * @param $key
	 * @param $value
	 * @param $ttl
	 * @return bool
	 */
	public function set($key, $value, $ttl) {
		return self::$instance->set($key, $value, $ttl);
	}

	/**
	 * Метод получает значение из кеша по $key
	 * @param $key
	 * @return mixed
	 */
	public function get($key) {
		return self::$instance->get($key);
	}
}

models/User.php
<?php

namespace app\models;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

controllers/MemcachedController.php
<?php

namespace app\controllers;

use app\models\MemcachedConfig;
use app\models\MemcachedVisor;
use Yii;

/**
 * Class MemcachedController
 *
 * Основной контроллер
 *
 * @package app\controllers
 */
class MemcachedController extends \yii\web\Controller {

	/**
	 * Вспомогательнвй метод возвращаюший объект MemcachedVisor
	 *
	 * @return MemcachedVisor
	 */
	private function getMemcached() {
		$memcachedConfig = new MemcachedConfig();
		$memcachedConfig->readConfig();
		$cfg = $memcachedConfig->getPreparedConfig();
		$memcached = new MemcachedVisor($cfg);
		return $memcached;
	}

	/**
	 * Метод контроллера ведущий на страницу с настройками
	 *
	 * @return string
	 */
	public function actionManager() {

		$memcachedConfig = new MemcachedConfig();

		if ($memcachedConfig->load(Yii::$app->request->post())) {
			$memcachedConfig->saveConfig();
		} else {
			$memcachedConfig->readConfig();
		}

		return $this->render('manager', [
			'model' => $memcachedConfig,
		]);
	}

	/**
	 * Метод контроллера ведущий на страницу с метриками
	 *
	 * @return string
	 */
	public function actionVisor() {

		$memcached = $this->getMemcached();
		$stats = $memcached->getStats();

		return $this->render('visor', [
			'servers' => $stats,
		]);
	}

	/**
	 * Метод контроллера записываюший 100 ключей с значением
	 * html кода сайта https://habrahabr.ru/
	 *
	 * @return string
	 */
	public function actionGenerate() {

		$memcached = $this->getMemcached();

		$text = file_get_contents('https://habrahabr.ru/');
		$i = 1;
		while ($i <= 100) {
			$i++;
			$key = 'key' . rand(1, 10000) . substr(md5(rand(1, 10000)), 2, 7);
			$memcached->set($key, $text, 600);
		}

		return $this->redirect('visor');
	}

	/**
	 * Метод контроллера устанавливаюший значение по ключу
	 *
	 * @return string
	 */
	public function actionSetValue() {

		$key = Yii::$app->request->post('key');
		$value = Yii::$app->request->post('value');

		$memcached = $this->getMemcached();
		$memcached->set($key, $value, 600);

		echo json_encode(sprintf('SET [key=%s, value=%s] OK', $key, $value));
		exit;
	}

	/**
	 * Метод контроллера получаюший значение по ключу
	 *
	 * @return string
	 */
	public function actionGetValue() {

		$key = Yii::$app->request->post('key');

		$memcached = $this->getMemcached();
		$value = $memcached->get($key);

		echo json_encode($value);
		exit;
	}

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Memcached-visor beta',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Visor', 'url' => ['/']],
            ['label' => 'Manager', 'url' => ['memcached/manager']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/memcached/manager.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>
    <h1>memcached/manager</h1>

    <div class="panel panel-primary">
        <div class="panel-heading">Config example</div>
        <div class="panel-body">
            10.252.17.207:11211<br>
            10.252.17.196:11211
        </div>
    </div>

<?php $form = ActiveForm::begin(); ?>
<?= $form->field($model, 'config')->textarea(['rows' => '6']) ?>
<?= Html::submitButton('save', ['class' => 'btn btn-success']) ?>
<?php ActiveForm::end(); ?>

views/memcached/visor.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use miloschuman\highcharts\Highcharts;
use yii\helpers\Url;
use yii\web\JsExpression;

?>
<h1>memcached/visor</h1>

<div class="panel-group" id="accordion">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="panel-title">Сontrol panel</h4>
        </div>
        <div class="panel-body">
            <div class="col-lg-4">
				<?php
				echo Html::a('Generate 100 random keys', ['memcached/generate'], ['class' => 'btn btn-info btn-group-justified']);
				echo Html::tag('br');
				echo Html::a('Refresh', ['/'], ['class' => 'btn btn-info  btn-group-justified']);
				?>
            </div>

            <div class="col-lg-4">
                <div class="input-group">
					<?= Html::input('textInput', 'key', 'key', ['id' => 'input-key', 'class' => 'form-control']); ?>
					<?= Html::input('textInput', 'value', 'value', ['id' => 'input-value', 'class' => 'form-control']); ?>
                    <span class="input-group-btn"><?= Html::button('set', ['class' => 'btn btn-info', 'id' => 'set-button']); ?></span>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="input-group">
					<?= Html::input('textInput', 'getkey', 'key', ['id' => 'input-get', 'class' => 'form-control']); ?>
					<?= Html::input('textInput', 'val', '', ['id' => 'output-val', 'class' => 'form-control', 'disabled' => 'disabled']); ?>
                    <span class="input-group-btn"><?= Html::button('get', ['class' => 'btn btn-info', 'id' => 'get-button']); ?></span>
                </div>
            </div>

        </div>
    </div>
	<?php
	$id = 0;
	/** @var array $servers */
	foreach ($servers as $server => $stats):
		$id++;
		?>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Server <?= $server; ?>
                </h4>
            </div>
            <div class="panel-body">
                <div class="container col-lg-5">
					<?php
					echo Html::ul($stats, ['item' => function ($value, $key) {
						$row = Html::a(Html::tag('span', $value, ['class' => 'label label-success pull-right']) . $key, '#');
						return Html::tag(
							'li',
							$row
						);
					}, 'class' => 'nav nav-pills nav-stacked']);
					?>
                </div>
                <div class="container col-lg-6" style="height: 500px">
					<?php
					echo Highcharts::widget([
						'scripts' => [
							'modules/exporting',
							'themes/grid-light',
						],
						'options' => [
							'title' => [
								'text' => 'Memcached charts',
							],
							'chart' => [
								'height' => 1000,
							],
							'series' => [
								[
									'type' => 'pie',
									'name' => 'Used RAM',
									'data' => [
										[
											'name' => 'Used, Kb',
											'y' => intval($stats['bytes'] / 1024),
											'color' => new JsExpression('Highcharts.getOptions().colors[0]'),
										],
										[
											'name' => 'Free, Kb',
											'y' => (intval($stats['limit_maxbytes'] / 1024) - intval($stats['bytes'] / 1024)),
											'color' => new JsExpression('Highcharts.getOptions().colors[1]'),
										],
									],
									'center' => [250, 125],
									'size' => 200,
									'showInLegend' => false,
									'dataLabels' => [
										'enabled' => true,
									],
								],
								[
									'type' => 'pie',
									'name' => 'total hits / total misses',
									'data' => [
										[
											'name' => 'HITS',
											'y' => intval($stats['get_hits']),
											'color' => new JsExpression('Highcharts.getOptions().colors[2]'),
										],
										[
											'name' => 'MISSES',
											'y' => intval($stats['get_misses']),
											'color' => new JsExpression('Highcharts.getOptions().colors[3]'),
										],
									],
									'center' => [250, 425],
									'size' => 200,
									'showInLegend' => false,
									'dataLabels' => [
										'enabled' => true,
									],
								],
								[
									'type' => 'pie',
									'name' => 'traffic',
									'data' => [
										[
											'name' => 'read, Kb',
											'y' => intval($stats['bytes_read'] / 1024),
											'color' => new JsExpression('Highcharts.getOptions().colors[9]'),
										],
										[
											'name' => 'write, Kb',
											'y' => intval($stats['bytes_written'] / 1024),
											'color' => new JsExpression('Highcharts.getOptions().colors[8]'),
										],
									],
									'center' => [250, 725],
									'size' => 200,
									'showInLegend' => false,
									'dataLabels' => [
										'enabled' => true,
									],
								],
							],
						]
					]);
					?>
                </div>
            </div>
        </div>
		<?php
	endforeach;
	?>
</div>
<script>
    $(function () {

        $('#set-button').click(function () {
            var setKey = $('#input-key').val();
            var setValue = $('#input-value').val();

            $.ajax({
                    dataType: 'json',
                    url: '<?= Url::toRoute(['/memcached/set-value'])?>',
                    type: 'POST',
                    data: {key: setKey, value: setValue}
                }
            ).fail(function () {
                    alert('Произошла ошибка при проверки сервера');
                }
            ).success(function (response) {
                    alert(response);
                }
            );
        });


        $('#get-button').click(function () {
            var getKey = $('#input-get').val();

            $.ajax({
                    dataType: 'json',
                    url: '<?= Url::toRoute(['/memcached/get-value'])?>',
                    type: 'POST',
                    data: {key: getKey}
                }
            ).fail(function () {
                    alert('Произошла ошибка при проверки сервера');
                }
            ).success(function (response) {
                    $('#output-val').val(response);
                }
            );
        });

    });
</script>